import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/layout/navbar";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Big Commerce App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Suspense>{children}</Suspense>
      </body>
    </html>
  );
}
